on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run nixpkgs#go -- build -ldflags="-s -w" -o hash-files ./hash-files.go
      - run: gh release create ${{ github.ref_name }} --generate-notes ./hash-files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
